isl: update to 0.21
- FIXME: Disable LTO.

/usr/lib/gcc/x86_64-aosc-linux-gnu/7.3.1/../../../../lib64/../lib64/Scrt1.o:init.c:function _start: error: undefined reference to 'main'
/tmp/cctUGNbA.ltrans0.ltrans.o:<artificial>:function isl_tab_sample_is_integer: error: undefined reference to '__gmpz_divisible_p'
/tmp/cctUGNbA.ltrans0.ltrans.o:<artificial>:function row_cmp.lto_priv.182: error: undefined reference to '__gmpz_mul'

...

- FIXME: compatibility symlink (19).